### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [DigitalNoteXDN/digitalnote#15]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support XDN on our service for a long time and we have been exchanging XDN for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by Snorting-Rum** [comment]
Hi Nicolas,
Not sure if anyone has got back to you directly, but if you join the Discord https://discordapp.com/invite/E6NQYwh  then message Kou (MD/Admin), Coca Cola, or AuCRHI who are the best point of contact.

Hope this helps :)
