### ISSUE TITLE
Does not build on gcc6

### ISSUE THREAD

**Issue by diablodude** [DigitalNoteXDN/digitalnote#6]
gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

/home/monero/digitalnote/src/crypto/crypto.cpp: In function ‘size_t Crypto::rs_comm_size(size_t)’:
/home/monero/digitalnote/src/crypto/crypto.cpp:338:58: error: value-initialization of incomplete type  Crypto::rs_comm::<anonymous struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);                                                                                              ^
src/CMakeFiles/Crypto.dir/build.make:158: recipe for target 'src/CMakeFiles/Crypto.dir/crypto/crypto.cpp.o' failed

**Comment by AuCRHI** [comment]
The latest code was patched to overcome that issue.
